### ISSUE TITLE
Auto-update 'last updated' time  (or remove)

### ISSUE THREAD

**Issue by tjhutton** [metasys-server/api-landing#14]
Can the last-update time be auto updated or, alternatively, removed? It does not reflect the last time the page was updated.

**Comment by mgwelch** [comment]
I would assume so. We use auto updated time on the API doc itself. Let's see if this was just an oversight, or if @ConnorChristie wanted to manage it manually.

**Comment by ConnorChristie** [comment]
Jekyll doesn't have any notion of when a page was last updated, only when the whole site itself was last updated. The last updated value on each page was designed to be updated manually.
